name: expressions
description: A library to parse and evaluate simple expressions.
version: 0.1.2
homepage: https://github.com/appsup-dart
author: Rik Bellens <rik.bellens@appsup.be>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  quiver: ">=0.24.0 <3.0.0"
  petitparser: ^3.0.0


dev_dependencies:
  test: ^1.0.0
